# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.4
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: 75947851+Asthay97@users.noreply.github.com
author_name: Astha Yadav
cloud_provider: netlify
contract_name: spinning_wheel
preset_name: production
project_name: spinning-wheel

